## Docs
- https://pandas.pydata.org/pandas-docs/stable/10min.html

In [1]:
import pandas as pd

In [9]:
df = pd.read_excel('mdtr_city.xlsx',header=1)

In [10]:
df

,CNPJ,Outlet,Cidade,2017/09,2017/10,2017/11,Total Geral
0,00002903000101,DROG STA RITA DE CANDIDO,CANDIDO MOTA,2.00,2.00,NaN,4.00
1,00005391000137,DROGARIA FARMA CRUZ,FRANCA,2.00,3.00,NaN,5.00
2,00006037000470,HOSPITAL UNIMED TATUI-JOSE FCO.M.DE ALMEIDA - DR.,TATUI,NaN,1.00,NaN,1.00
3,00006290000180,DROGARIA CAMPEA POPULAR,SAO PAULO,3.00,2.00,NaN,5.00
4,00006290000199,DROGARIA CAMPEA POPULAR,SAO PAULO,3.00,3.00,NaN,6.00
5,00006486000175,DROGARIA SAO FRANCISCO DE ASSIS,ANICUNS,2.00,NaN,NaN,2.00
6,00011976000160,DROGARIA MAIS FORMOSA,SAO PAULO,1.00,NaN,NaN,1.00
7,00013246000106,DROG SOUZA,CAMPINAS,1.00,1.00,NaN,2.00
8,00017373000175,DROG CALONI LTDA ME,DRACENA,3.00,2.50,NaN,5.50
9,00019968000160,DROGARIA NACIONAL,BRASILIA,1.50,NaN,NaN,1.50
10,00020717000103,FCIA DESCONTAO,ARACATUBA,2.00,1.50,NaN,3.50
11,00022548000132,FARMASUL GEISEL,BAURU,1.00,NaN,NaN,1.00
12,00025528000115,DROG JANINEFARMA LTDA,QUIRINOPOLIS,NaN,0.50,NaN,0.50
13,00028656000112,DROG SAUDE II,SAO JOSE DO RIO PRETO,39.00,31.50,2.00,72.50
14,00028656000199,DROG SAUDE II,SAO JOSE DO RIO PRETO,17.00,29.00,NaN,46.00
15,00030181000107,DROGARIA PRO VITA,GUARULHOS,7.00,8.50,NaN,15.50
16,00030181000280,DROGARIA PRO VITA,GUARULHOS,13.50,11.00,NaN,24.50
17,00030181000360,DROGARIA PRO VITA,SAO PAULO,2.00,NaN,NaN,2.00
18,00030181000603,DROGARIA PRO VITA,SAO PAULO,4.00,2.00,NaN,6.00
19,00030181000794,DROGARIA PRO VITA,GUARULHOS,4.00,8.50,NaN,12.50
20,00030181000875,DROGARIA PRO VITA,SAO PAULO,7.00,7.50,NaN,14.50
21,00030181000956,DROGARIA PRO VITA LTDA,SAO PAULO,7.00,16.00,NaN,23.00
22,00032532000100,DROGARIA LUCIA LTDA,ANAPOLIS,9.00,15.00,NaN,24.00
23,00037259000107,DROG SAO MATEUS LTDA,ANAPOLIS,0.50,NaN,NaN,0.50
24,00049791000144,HOSPITAL SANTA HELENA,BRASILIA,2.50,NaN,NaN,2.50
25,00053082000132,FARMACIA DO JOAO BOSCO,BELA VISTA DE GOIAS,0.50,2.25,NaN,2.75
26,00058542000115,HIPERFARMA,CURITIBA,NaN,0.50,NaN,0.50
27,00058816000176,DROG BETEL DE PIEDADE,RIO DE JANEIRO,NaN,NaN,0.50,0.50
28,00059344000176,DROGARIA AVENIDA,CACERES,1.00,NaN,NaN,1.00
29,00060726000110,RUY SUPLICY WIEDMER,LAPA,7.00,6.50,1.00,14.50
...,...,...,...,...,...,...,...
31308,BN0852023,PE/1160_852-23,RECIFE,2.00,NaN,NaN,2.00
31309,BN0856001,PE/1160_856-1,RECIFE,6.00,5.00,NaN,11.00
31310,BN0856002,PE/1160_856-2,RECIFE,2.00,NaN,NaN,2.00
31311,BN0856004,PE/1160_856-4,RECIFE,2.00,NaN,NaN,2.00
31312,BN0856005,PE/1160_856-5,RECIFE,1.00,NaN,NaN,1.00
31313,BN0860011,PE/960_860-11,OLINDA,NaN,3.00,NaN,3.00
31314,BN1071001,DF/10_1071-1,BRASILIA,7.00,NaN,NaN,7.00
31315,BN1073001,DF/10_1073-1,BRASILIA,NaN,NaN,2.00,2.00
31316,BN1074001,DF/10_1074-1,BRASILIA,NaN,2.00,NaN,2.00
31317,BN1080001,DF/10_1080-1,BRASILIA,1.00,NaN,NaN,1.00
31318,BN1081007,DF/10_1081-7,BRASILIA,NaN,1.00,NaN,1.00
31319,BN1081021,DF/10_1081-21,BRASILIA,NaN,1.00,NaN,1.00
31320,BN1082001,DF/10_1082-1,BRASILIA,NaN,2.00,NaN,2.00
31321,BN1082013,DF/10_1082-13,BRASILIA,1.00,NaN,NaN,1.00
31322,BN1089001,GO/870_1089-1,GOIANIA,6.50,NaN,NaN,6.50
31323,BN1092001,GO/870_1092-1,GOIANIA,1.00,1.00,NaN,2.00
31324,BN1092002,GO/870_1092-2,GOIANIA,NaN,1.00,NaN,1.00
31325,BN1093011,GO/870_1093-11,GOIANIA,NaN,1.00,NaN,1.00
31326,BN1099002,GO/870_1099-2,GOIANIA,2.00,NaN,NaN,2.00
31327,BN1105006,GO/870_1105-6,GOIANIA,NaN,1.50,NaN,1.50
31328,BN1171001,PR/690_1171-1,CURITIBA,NaN,1.00,NaN,1.00
31329,BN1176001,PR/690_1176-1,CURITIBA,0.50,NaN,NaN,0.50
31330,BN1219001,PR/1370_1219-1,LONDRINA,NaN,4.00,NaN,4.00
31331,BN1221002,PR/1370_1221-2,LONDRINA,NaN,0.50,NaN,0.50
31332,BN1241009,PR/1520_1241-9,MARINGA,1.00,NaN,NaN,1.00
31333,BN1322019,RS/920_1322-19,GRAVATAI,NaN,1.00,NaN,1.00
31334,BO8152001,OUTROS - BRICK 0152001,SANTO ANDRE,2.00,NaN,NaN,2.00
31335,BO8162001,OUTROS - BRICK 0162001,SAO BERNARDO DO CAMPO,NaN,1.00,NaN,1.00
31336,BO8837008,OUTROS - BRICK 0837008,RECIFE,NaN,1.50,NaN,1.50
31337,Total Geral,NaN,NaN,168448.75,171974.50,17606.75,358030.00

In [12]:
df.columns['CNPJ','Outlet', 'Cidade', '2017/09', '2017/10', '2017/11', 'Total']

TypeError: 'Index' object is not callable

In [29]:
df.describe()

,Cx Pad Mensal,Unnamed: 1,Unnamed: 2,Competencia,Unnamed: 4,Unnamed: 5,Unnamed: 6
count,31339,31338,31333,24123,24601,7200,31339
unique,31339,12533,3354,348,370,89,555
top,61585865148060,FARMACIAS PAGUE MENOS,SAO PAULO,1,1,1,1
freq,1,1012,2307,5295,5360,2638,5380

In [30]:
df.head(5)

,Cx Pad Mensal,Unnamed: 1,Unnamed: 2,Competencia,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,CNPJ,Outlet,Cidade,2017/09,2017/10,2017/11,Total Geral
1,00002903000101,DROG STA RITA DE CANDIDO,CANDIDO MOTA,2,2,NaN,4
2,00005391000137,DROGARIA FARMA CRUZ,FRANCA,2,3,NaN,5
3,00006037000470,HOSPITAL UNIMED TATUI-JOSE FCO.M.DE ALMEIDA - DR.,TATUI,NaN,1,NaN,1
4,00006290000180,DROGARIA CAMPEA POPULAR,SAO PAULO,3,2,NaN,5

In [26]:
df.columns

Index(['Cx Pad Mensal', 'Unnamed: 1', 'Unnamed: 2', 'Competencia',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')

In [27]:
df.index

RangeIndex(start=0, stop=31339, step=1)

In [13]:
df_csv = pd.read_csv('mdtr_city.csv', sep=';')

In [18]:
print(df_csv['2903000101'])

0         5391000137
1         6037000470
2         6290000180
3         6290000199
4         6486000175
5        11976000160
6        13246000106
7        17373000175
8        19968000160
9        20717000103
10       22548000132
11       25528000115
12       28656000112
13       28656000199
14       30181000107
15       30181000280
16       30181000360
17       30181000603
18       30181000794
19       30181000875
20       30181000956
21       32532000100
22       37259000107
23       49791000144
24       53082000132
25       58542000115
26       58816000176
27       59344000176
28       60726000110
29       61325000184
            ...
31307      BN0852023
31308      BN0856001
31309      BN0856002
31310      BN0856004
31311      BN0856005
31312      BN0860011
31313      BN1071001
31314      BN1073001
31315      BN1074001
31316      BN1080001
31317      BN1081007
31318      BN1081021
31319      BN1082001
31320      BN1082013
31321      BN1089001
31322      BN1092001
31323      BN1092002
31324      BN1093011
31325      BN1099002
31326      BN1105006
31327      BN1171001
31328      BN1176001
31329      BN1219001
31330      BN1221002
31331      BN1241009
31332      BN1322019
31333      BO8152001
31334      BO8162001
31335      BO8837008
31336    Total Geral
Name: 2903000101, Length: 31337, dtype: object